USE %s;
CREATE TABLE IF NOT EXISTS users(username varchar, password varchar, roles set<text>, PRIMARY KEY (username));
INSERT INTO users (username, password, roles) VALUES('Robin_Van_Persie', 'Feyenoord', {'ROLE_USER'});
INSERT INTO users (username, password, roles) VALUES('Cristiano', 'Ronaldo', {'ROLE_USER'});
INSERT INTO users (username, password, roles) VALUES('admin', 'admin', {'ROLE_ADMIN'});