# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = {
  ###  prefix => [ip_start,memory_allocated(in MBs)]
  
  'services' => [100,2048],
  'cassandra' => [150,1024],
  'ecloud-swift1' => [210,1024]
  #,
  # 'ecloud-swift2' => [220,768],
  # 'ecloud-swift3' => [230,768],
}

Vagrant.configure("2") do |config|
  #precise64 is an alias for ubuntu 12.04 LTS
  config.vm.box     = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  nodes.each do |prefix,(ip_start,memory_allocated)|
    hostname = "%s" % [prefix]
    config.vm.define "#{hostname}" do |box|
      box.vm.hostname = "#{hostname}"
      #install 3 interfaces for each node
      #eth1
      box.vm.network :private_network, ip: "172.16.0.#{ip_start}", :netmask => "255.255.0.0"
      #eth2
      box.vm.network :private_network, ip: "10.10.0.#{ip_start}", :netmask => "255.255.0.0" 
      #eth3
      box.vm.network :private_network, ip: "192.168.100.#{ip_start}", :netmask => "255.255.255.0" 
      box.vm.network :forwarded_port, guest: 22, host: "22#{ip_start}"

      #execute the provision scripts
      box.vm.provision :shell, :path => "common.sh"
      box.vm.provision :shell, :path => "#{prefix}.sh"


      box.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", "#{memory_allocated}"]
        vbox.customize ["modifyvm", :id, "--cpus", 1]
        vbox.name = "#{prefix}"
      end
    end
  end
end
